[target]
dir = "./demo_codebase"

[analyzer]
exclude = ["**/__pycache__/**", "**/.venv/**", "**/tests/**"]
# Only analyze these files/dirs (optional). If commented out, analyze all language-default files.
# includeOnly = ["demo_codebase/**", "demo_codebase/ts/**"]
# Suppress edges/imports to these modules (e.g., external libs)
excludeModules = []

[output]
dir = "out/demo_codebase"  # Folder relative to this config; will contain codebase_graph.json

[tags]
project = ["llm", "expensive", "cli-entrypoint"]

[viewer]
layout = "elk-then-fcose"
# mode = "default"
# host = "127.0.0.1"
# port = 8080




