[target]
dir = "/Users/greg/Dropbox/dev/experim/hellozenno/backend"

[analyzer]
exclude = ["**/__pycache__/**", "**/.venv/**", "**/tests/**"]
# Only analyze these files/dirs (optional). If commented out, analyze all .py files.
# includeOnly = ["**/*.py"]
# Suppress edges/imports to these modules (e.g., external libs)
excludeModules = []

[output]
dir = "../out/<target>"  # Folder relative to this config; will contain codebase_graph.json

[tags]
project = ["llm", "expensive", "cli-entrypoint"]

[viewer]
layout = "elk-then-fcose"
port = 8001


